ALTER TABLE ONLY book_tags
    ADD CONSTRAINT book_fk FOREIGN KEY (book_id) REFERENCES books(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;

ALTER TABLE ONLY book_tags
    ADD CONSTRAINT tag_fk FOREIGN KEY (tag_id) REFERENCES tags(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;

ALTER TABLE ONLY comments
    ADD CONSTRAINT book_fk FOREIGN KEY (book_id) REFERENCES books(id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;;

ALTER TABLE ONLY books
    ADD CONSTRAINT pub_fk FOREIGN KEY (pub_id) REFERENCES publishers(id) ON UPDATE SET NULL ON DELETE SET NULL NOT VALID;

